chore: Update package installation messages and add timeout for wget downloads

diff --git a/ishare2 b/ishare2
--- a/ishare2
+++ b/ishare2
@@ -633,7 +633,7 @@ install_dependencies() {
     for package in "${packages[@]}"; do
         echo -e "${YELLOW} -${NO_COLOR} $package"
     done
-    echo -e "${YELLOW}[+] Installing dependencies in 5 seconds... Press Ctrl+C to cancel.${NO_COLOR}"
+    echo -e "${YELLOW}[+] Starting to install dependencies in 5 seconds... This may take a while. Press Ctrl+C to cancel.${NO_COLOR}"
     sleep 5
 
     for package in "${packages[@]}"; do
@@ -645,7 +645,7 @@ install_dependencies() {
 check_installed() {
     PACKAGE=$1
     # Check if package is installed
-    if ! command -v jq &>/dev/null; then
+    if ! command -v "$PACKAGE" &>/dev/null; then
         echo -e "${YELLOW}[!] WARN: $PACKAGE is not installed.${NO_COLOR}"
         install_package "$PACKAGE"
         # Check success of package installation
@@ -714,6 +714,7 @@ fix_repositories() {
 
 # Function to run apt-get update
 apt_get_update() {
+    echo -e "${YELLOW}[+] Updating package lists...${NO_COLOR}"
     if ! apt-get update -y -qq; then
         return 1
     fi
@@ -725,7 +726,6 @@ install_package() {
     # check if $package_name is installed otherwise install it
     if ! command -v "$package_name" &>/dev/null; then
         echo -e "${YELLOW}[+] $package_name is not installed.${NO_COLOR}"
-        echo -e "${YELLOW}[+] Updating package lists...${NO_COLOR}"
         if ! apt_get_update; then
             echo -e "${RED}[-] Failed to update package lists.${NO_COLOR}"
             echo -e "${YELLOW}[!] Attempting to fix APT sources...${NO_COLOR}"
@@ -745,6 +745,7 @@ install_package() {
             exit 1
         fi
     else
+        echo -e "${GREEN}[+] $package_name is already installed.${NO_COLOR}"
         logger info "Package $package_name is already installed."
         logger info "Updating $package_name..."
         if ! apt-get install --only-upgrade -qq "$package_name"; then
@@ -1008,9 +1009,9 @@ download_file_wget() {
     logger info "Downloading file from $url..."
 
     if [ "$SSL_CHECK" = true ]; then
-        wget -O "$output" "$url" -q --show-progress --content-disposition
+        wget -O "$output" "$url" -q --show-progress --content-disposition -T 300
     else
-        wget -O "$output" "$url" -q --show-progress --content-disposition --no-check-certificate
+        wget -O "$output" "$url" -q --show-progress --content-disposition --no-check-certificate -T 300
     fi
 
     # Check if wget command failed
@@ -2259,6 +2260,7 @@ pull_images() {
     download_path=$(jq -r --arg type "$IMAGE_TYPE" --arg id "$IMAGE_ID" '.[$type][] | select(.id == ($id | tonumber)) | .download_path' "$TEMP_JSON")
     image_name=$(jq -r --arg type "$IMAGE_TYPE" --arg id "$IMAGE_ID" '.[$type][] | select(.id == ($id | tonumber)) | .name' "$TEMP_JSON")
     image_size=$(jq -r --arg type "$IMAGE_TYPE" --arg id "$IMAGE_ID" '.[$type][] | select(.id == ($id | tonumber)) | .human_readable_size' "$TEMP_JSON")
+    image_size_bytes=$(jq -r --arg type "$IMAGE_TYPE" --arg id "$IMAGE_ID" '.[$type][] | select(.id == ($id | tonumber)) | .size' "$TEMP_JSON")
 
     # 2. Download the image(s) for the specified type and ID
     # Skip download if the image is already installed
@@ -2315,11 +2317,14 @@ pull_images() {
         "QEMU")
             for download_url in $download_urls; do
                 download_file "$download_url" "$download_path"
+                check_image_size "$download_path" "$image_name" "$image_size_bytes"
             done
             ;;
         "BIN" | "DYNAMIPS" | "IOL")
             for download_url in $download_urls; do
                 download_file "$download_url" "$download_path" "$image_name"
+                # Check image size against the downloaded file
+                check_image_size "$download_path" "$image_name" "$image_size_bytes"
             done
             ;;
         *)
@@ -2329,7 +2334,8 @@ pull_images() {
 
         echo -e "${YELLOW}[+] ${BLUE}DOWNLOAD COMPLETED! ${NO_COLOR}"
     else
-        echo "Image not found for Type: $IMAGE_TYPE, ID: $IMAGE_ID"
+        echo "Image id $IMAGE_ID ($image_name) not found for type $IMAGE_TYPE in the index of images"
+        exit 1
     fi
 
     # 3. Handle downloaded files if TYPE is QEMU
