Skip SSL check flags feature. Allow to set in configuration file

diff --git a/ishare2 b/ishare2
--- a/ishare2
+++ b/ishare2
@@ -60,10 +60,11 @@ function switch_downloader() {
 }
 
 function create_config() {
-    echo -e "${YELLOW} [+] Creating ishare2 configuration file...${NO_COLOR}"
-    echo -e "${YELLOW} [+] Please answer the following questions to configure ishare2.${NO_COLOR}"
-    echo -e "${YELLOW} [+] Press enter to use the default values which should work out of the box.${NO_COLOR}"
-    echo -e "${YELLOW} [+] Press Ctrl+C to cancel.${NO_COLOR}"
+    echo -e "${YELLOW} [*] Creating ishare2 configuration file...${NO_COLOR}"
+    echo -e "${YELLOW} [*] Please answer the following questions to configure ishare2.${NO_COLOR}"
+    echo -e "${YELLOW} [*] Press enter to use the default values which should work out of the box.${NO_COLOR}"
+    echo -e "${YELLOW} [*] Press Ctrl+C to cancel.${NO_COLOR}"
+    # Ask whether to use aria2c or not
     echo -e "${YELLOW} [+] Use aria2c for faster downloads?${NO_COLOR}"
     read -p " [+] (y/n): " -r
     if [[ $REPLY =~ ^[Yy]$ ]]; then
@@ -79,14 +80,26 @@ function create_config() {
         read -n 1
     fi
 
-    # Ask for the channel value
-    echo -e "${YELLOW} [+] Select the channel:${NO_COLOR}"
-    echo "  1) main"
-    echo "  2) alpha"
-    read -p " [+] Enter the channel number (default: 1): " -r
+    # Ask if SSL certificate should be checked
+    echo -e "${YELLOW} [+] Check SSL certificate? (default: yes)${NO_COLOR}"
+    read -p " [+] (y/n): " -r
     case $REPLY in
-    2)
-        CHANNEL="alpha"
+    [Nn])
+        SSL_CHECK=false
+        ;;
+    *)
+        SSL_CHECK=true
+        ;;
+    esac
+    echo "SSL_CHECK=\"$SSL_CHECK\"" >>$ISHARE2_DIR/ishare2.conf
+
+    # Ask for the channel value
+    echo -e "${YELLOW} [+] Choose the update channel.${NO_COLOR}"
+    echo "  1) main"
+    read -p " [+] Enter the update channel option (default: 1): " -r
+    case $REPLY in
+    1)
+        CHANNEL="main"
         ;;
     *)
         CHANNEL="main"
@@ -100,6 +113,7 @@ function create_config() {
         exit 1
     fi
     remove_duplicates
+    validate_conf_file
 }
 
 remove_duplicates() {
@@ -114,7 +128,7 @@ remove_duplicates() {
     # Remove duplicate lines from the configuration file
     awk '!seen[$0]++' "$config_file" >"$config_file.tmp" && mv "$config_file.tmp" "$config_file"
 
-    echo -e "${GREEN} [+] Duplicates removed from the configuration file.${NO_COLOR}"
+    echo -e "${GREEN} [+] Duplicates removed from the configuration file.${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
 }
 
 validate_conf_file() {
@@ -127,7 +141,7 @@ validate_conf_file() {
     fi
 
     # Array of allowed variables
-    local allowed_vars=("USE_ARIA2C" "CHANNEL")
+    local allowed_vars=("USE_ARIA2C" "CHANNEL" "SSL_CHECK")
 
     # Read the configuration file line by line and filter out invalid variables
     local filtered_content=""
@@ -144,14 +158,14 @@ validate_conf_file() {
         if [[ " ${allowed_vars[@]} " =~ " $var_name " ]]; then
             filtered_content+="$line"$'\n'
         else
-            echo -e "${RED} [!] Removing invalid variable from the configuration file: $line.${NO_COLOR}"
+            echo -e "${RED} [!] Removing invalid variable from the configuration file: $line.${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
         fi
     done <"$config_file"
 
     # Write the filtered content back to the configuration file
     echo "$filtered_content" >"$config_file"
 
-    echo -e "${GREEN} [+] Configuration file validated and updated.${NO_COLOR}" >$ISHARE2_DIR/logs.txt
+    echo -e "${GREEN} [+] Configuration file validated and updated.${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
     source "$config_file"
     return 0
 }
@@ -249,27 +263,6 @@ function fetch_sources() {
     echo -e "${GREEN} [+] Done.${NO_COLOR}"
 }
 
-download_file_curl() {
-    # Create the directory if it does not exist
-    mkdir -p $ISHARE2_DIR/tmp
-    # Create the file if it does not exist
-    touch $ISHARE2_DIR/tmp/curl_error
-    local url="$1"
-    local output="$2"
-    echo -e "${YELLOW} [+] Downloading file from $url... ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
-    if curl -s -o "$output" "$url" 2>$ISHARE2_DIR/tmp/curl_error; then
-        echo -e "${GREEN} [+] The file has been downloaded successfully to $output. ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
-        rm -f $ISHARE2_DIR/tmp/curl_error
-    else
-        echo -e "${RED} [-] Error: Unable to download the file. ${NO_COLOR}"
-        # Read the error message from the curl_error file
-        ERROR_MESSAGE=$(cat $ISHARE2_DIR/tmp/curl_error)
-        # Print the error message
-        echo -e "${RED} [-] Logs:\n $ERROR_MESSAGE ${NO_COLOR}"
-        exit 1
-    fi
-}
-
 download_file() {
     local url="$1"
     local output="$2"
@@ -305,11 +298,44 @@ download_file_aria2() {
 
     echo -e "${YELLOW} [+] Downloading file from $url... ${NO_COLOR}"
     rm -f error.log
-    if aria2c --console-log-level=warn -j 2 -c --split=4 --min-split-size=20M --max-connection-per-server=4 --download-result=hide --check-certificate=false --allow-overwrite=true --dir="$output_dir" --out="$output_name" --log="error.log" "$url"; then
+    if [ "$SSL_CHECK" = true ]; then
+        aria2c --console-log-level=warn -j 2 -c --split=4 --min-split-size=20M --max-connection-per-server=4 --download-result=hide --allow-overwrite=true --dir="$output_dir" --out="$output_name" --log="error.log" "$url"
+    else
+        aria2c --console-log-level=warn -j 2 -c --split=4 --min-split-size=20M --max-connection-per-server=4 --download-result=hide --check-certificate=false --allow-overwrite=true --dir="$output_dir" --out="$output_name" --log="error.log" "$url"
+    fi
+
+    if [ $? -eq 0 ]; then
         echo -e "${GREEN} [+] The file has been downloaded successfully to $output_dir/$output_name. ${NO_COLOR}"
         rm -f error.log
     else
         echo -e "${RED} [-] Error: Unable to download the file. Check the error.log file for more information.${NO_COLOR}"
+        exit 1
+    fi
+}
+
+download_file_curl() {
+    # Create the directory if it does not exist
+    mkdir -p $ISHARE2_DIR/tmp
+    # Create the file if it does not exist
+    touch $ISHARE2_DIR/tmp/curl_error
+    local url="$1"
+    local output="$2"
+    echo -e "${YELLOW} [+] Downloading file from $url... ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
+    if [ "$SSL_CHECK" = true ]; then
+        curl -s -o "$output" "$url" 2>$ISHARE2_DIR/tmp/curl_error
+    else
+        curl -s --insecure -o "$output" "$url" 2>$ISHARE2_DIR/tmp/curl_error
+    fi
+
+    if [ $? -eq 0 ]; then
+        echo -e "${GREEN} [+] The file has been downloaded successfully to $output. ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
+        rm -f $ISHARE2_DIR/tmp/curl_error
+    else
+        echo -e "${RED} [-] Error: Unable to download the file. ${NO_COLOR}"
+        # Read the error message from the curl_error file
+        ERROR_MESSAGE=$(cat $ISHARE2_DIR/tmp/curl_error)
+        # Print the error message
+        echo -e "${RED} [-] Logs:\n $ERROR_MESSAGE ${NO_COLOR}"
         exit 1
     fi
 }
@@ -328,18 +354,24 @@ download_file_wget() {
     fi
     local output="$output_dir/$output_name"
     echo -e "${YELLOW} [+] Downloading file from $url... ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
+
+    if [ "$SSL_CHECK" = true ]; then
     wget -O "$output" "$url" -q --show-progress --content-disposition
+    else
+        wget -O "$output" "$url" -q --show-progress --content-disposition --no-check-certificate
+    fi
+
     # Check if wget command failed
-    if [[ $? -ne 0 ]]; then
+    if [ $? -eq 0 ]; then
+        echo -e "${GREEN} [+] The file has been downloaded successfully to $output. ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
+        rm -f $ISHARE2_DIR/tmp/wget_error
+    else
         echo -e "${RED} [-] Error: Unable to download the file. ${NO_COLOR}"
         # Read the error message from the wget_error file
         ERROR_MESSAGE=$(cat $ISHARE2_DIR/tmp/wget_error)
         # Print the error message
         echo -e "${RED} [-] Logs:\n $ERROR_MESSAGE ${NO_COLOR}"
         exit 1
-    else
-        echo -e "${GREEN} [+] The file has been downloaded successfully to $output. ${NO_COLOR}" >>$ISHARE2_DIR/logs.txt
-        rm -f $ISHARE2_DIR/tmp/wget_error
     fi
 }
 
