Reuse create dir function

diff --git a/ishare2 b/ishare2
--- a/ishare2
+++ b/ishare2
@@ -256,24 +256,17 @@ function unlock_dpkg() {
 
 function create_ishare2_dir() {
     echo -e "${YELLOW} [+] Creating ishare2 directory...${NO_COLOR}"
-    if ! mkdir -p $ISHARE2_DIR 2>/dev/null; then
-        error_message=$(mkdir -p $ISHARE2_DIR 2>&1 >/dev/null)
+    for dir in $ISHARE2_DIR $ISHARE2_DIR/tmp; do
+        if ! mkdir -p "$dir" 2>/dev/null; then
+            error_message=$(mkdir -p "$dir" 2>&1 >/dev/null)
         if [[ $error_message == *"Permission denied"* ]]; then
-            echo -e "${RED} [-] Failed to create ishare2 directory: Permission denied.${NO_COLOR}"
+                echo -e "${RED} [-] Failed to create $dir: Permission denied.${NO_COLOR}"
         else
-            echo -e "${RED} [-] Failed to create ishare2 directory. Error: $error_message${NO_COLOR}"
+                echo -e "${RED} [-] Failed to create $dir. Error: $error_message${NO_COLOR}"
         fi
         exit 1
     fi
-    if ! mkdir -p $ISHARE2_DIR/tmp 2>/dev/null; then
-        error_message=$(mkdir -p $ISHARE2_DIR/tmp 2>&1 >/dev/null)
-        if [[ $error_message == *"Permission denied"* ]]; then
-            echo -e "${RED} [-] Failed to create ishare2 directory: Permission denied.${NO_COLOR}"
-        else
-            echo -e "${RED} [-] Failed to create ishare2 directory. Error: $error_message${NO_COLOR}"
-        fi
-        exit 1
-    fi
+    done
     echo -e "${GREEN} [+] Done.${NO_COLOR}"
 }
 
