Fix APT sources and improve error handling

diff --git a/ishare2 b/ishare2
--- a/ishare2
+++ b/ishare2
@@ -419,7 +419,31 @@ check_installed() {
             echo -e "${RED} [-] Error: Failed to install $PACKAGE.${NO_COLOR}"
             exit 1
         else # package is installed
-            echo -e "${GREEN} [+] $PACKAGE has been installed successfully.${NO_COLOR}"
+            echo -e "${GREEN}[+] $PACKAGE has been installed successfully.${NO_COLOR}"
+        fi
+    fi
+}
+
+is_site_accessible() {
+    local url=$1
+    if ! curl -s --head --request GET "$url" | grep "200 OK\|301 Moved Permanently" >/dev/null; then
+        return 1 # Site is not accessible
+    else
+        return 0 # Site is accessible
+    fi
+}
+
+fix_repositories() {
+    if is_site_accessible "https://repo.pnetlab.com"; then
+        echo -e "${GREEN}[+] repo.pnetlab.com is accessible.${NO_COLOR}"
+    else
+        echo -e "${YELLOW}[!] repo.pnetlab.com is not accessible. Checking alternative...${NO_COLOR}"
+        if is_site_accessible "https://pnetlab.labhub.eu.org"; then
+            replace_pnetlab_sources
+            apt_get_update || echo -e "${RED}[-] Failed to update package lists after replacing sources.${NO_COLOR}"
+        else
+            echo -e "${RED}[-] Both repo.pnetlab.com and the alternative pnetlab.labhub.eu.org are inaccessible.${NO_COLOR}"
+            exit 1
         fi
     fi
 }
@@ -438,11 +462,12 @@ install_package() {
     unlock_dpkg
     # check if $package_name is installed otherwise install it
     if ! command -v "$package_name" &>/dev/null; then
-        echo -e "${YELLOW} [+] $package_name is not installed.${NO_COLOR}"
-        echo -e "${YELLOW} [+] Updating package lists...${NO_COLOR}"
-        if ! apt-get update; then
-            echo -e "${RED} [-] Failed to update package lists.${NO_COLOR}"
-            exit 1
+            echo -e "${YELLOW}[!] Attempting to fix APT sources...${NO_COLOR}"
+            fix_repositories
+            if ! apt_get_update; then
+                echo -e "${RED}[-] Failed to fix APT sources.${NO_COLOR}"
+                exit 1
+            fi
         fi
 
         echo -e "${YELLOW} [+] Installing $package_name...${NO_COLOR}"
